- name: Ejecutar el comando whoami
  command: whoami
  register: whoami_output

- name: Mostrar el resultado de whoami
  debug:
    msg: "El resultado de whoami es: {{ whoami_output.stdout }}"

- name: Update packet list
  become: yes
  apt:
    update_cache: yes

- name: Install skopeo
  become: yes
  apt:
    name: skopeo
    state: present

- name: Autenticarse en skopeo
  command: skopeo login -u alegazCP2ContainerRegistry -p {{ registry_password }} alegazCP2ContainerRegistry.azurecr.io

- name: Copia repo en acr
  command: skopeo copy docker://docker.io/nginx:latest docker://alegazCP2ContainerRegistry.azurecr.io/nginx:latest

- name: Copia repo en acr
  command: skopeo copy docker://mcr.microsoft.com/azuredocs/azure-vote-front:v1 docker://alegazCP2ContainerRegistry.azurecr.io/azure-vote-front:v1

- name: Copia repo en acr
  command: skopeo copy docker://mcr.microsoft.com/oss/bitnami/redis:6.0.8 docker://alegazCP2ContainerRegistry.azurecr.io/redis:6.0.8

