- name: Execute whoami command
  command: whoami
  register: whoami_output

- name: Show whoami command result
  debug:
    msg: "El resultado de whoami es: {{ whoami_output.stdout }}"

- name: Update packet list
  become: yes
  apt:
    update_cache: yes

- name: Install skopeo
  become: yes
  apt:
    name: skopeo
    state: present

- name: Login on skopeo
  command: skopeo login -u alegazCP2ContainerRegistry -p {{ registry_password }} alegazCP2ContainerRegistry.azurecr.io

- name: Copy NGINX container image  in ACR
  command: skopeo copy docker://docker.io/nginx:latest docker://alegazCP2ContainerRegistry.azurecr.io/nginx:latest

- name: Copy Azure Vote Front container image in ACR
  command: skopeo copy docker://mcr.microsoft.com/azuredocs/azure-vote-front:v1 docker://alegazCP2ContainerRegistry.azurecr.io/azure-vote-front:v1

- name: Copy Redis container image  in ACR
  command: skopeo copy docker://mcr.microsoft.com/oss/bitnami/redis:6.0.8 docker://alegazCP2ContainerRegistry.azurecr.io/redis:6.0.8

