- name: Logging on Azure Account
  command: az login -u alvargines.legaz053@comunidadunir.net -p {{ registry_az_password }}

- name: Get AKS creddentials 
  command: az aks get-credentials --resource-group CP2_ResourceGroup  --name alegazk8s --overwrite-existing

- name: Deploy services in AKS  
  ansible.builtin.shell: |
        kubectl apply -f /home/alegaz/Desktop/Curso_DevOps_Cloud/CP2_Cloud/kubernetes/k8s_vote_app.yaml
  
- name: Verify deploy   
  command: kubectl get services


