---
- hosts: local
  vars_prompt:

    - name: "registry_az_password"
      prompt: "Azure account password"
      private: yes
      
    - name: "registry_password"
      prompt: "Azure container register password"
      private: yes
 
  roles:
    - acr
    - aks

- hosts: vm1_azure
  vars_prompt:

    - name: "registry_password"
      prompt: "Azure container register password"
      private: yes
 
  roles:
    - vm_and_nginx
