---
- hosts: vm1_azure
  vars_prompt:
    - name: "registry_username"
      prompt: "Azure container register username"
      private: no

    - name: "registry_password"
      prompt: "Password"
      private: yes
  roles:
    - acr
    - vm_and_nginx

